%YAML:1.0

# akaze61 parameters

# Feature Extractor 
FeatureExtractor.numOctaves: 8
FeatureExtractor.scaleFactor: 1.1892 # 2^0.25
FeatureExtractor.detectionTh: 0.0005

# Feature Matcher 
FeatureMatcher.matchingTh: 128.0
